services:
  - type: web
    name: btc-price-tracker-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python btc_bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: CHECK_INTERVAL_SECONDS
        value: "60"
